language: ruby
script: bundle exec rspec
before_install:
- gem update bundler
rvm:
- 2.4.1
- 2.3.4
- 2.2.7
env:
- ISOLATED=true
- ISOLATED=false
git:
  depth: 2
  submodules: false
dd:
  secure: fzItORKaVrevTjQQu85FYgqgSVkRGG8PtOfNTCYY0meyP1+hF/lH6i5ZAb35VAuwi9InqaYnPx09dREBlfEqkzY/Ypxglq+EosAfqOgiKFu44JlM4vhxSdwn2mywCJpYZ0IbH5OnkF6rUULL/AoRQPlIV77eRqhB9LGfLNlYMfU=
